server.port: 8080

general:
  base-url: http://localhost:8080

k8s:
  watch:
    scheduled: 60000
    setup: 600000

watchfor:
  log-rules:
  - name: generic-exception-check
    description: a generic check to find Exceptions
    matches-in-or:
    - how-many: 3
      how-much: 120000
      values-in-and:
      - ERROR
      - Caused by
    - how-many: 3
      how-much: 120000
      values-in-and:
      - ERROR
      - Exception
    selectors-in-and:
    - namespace-match:
      - development

handlers:
  delete-pod:
    enabled: true
  reset-analysis:
    enabled: true

notifiers:
  noop:
    enabled: true
    single-template: "Looks like {{pod-namespace}}/{{pod-name}} has a match with {{rule-description}}. I could do the following:\n\n - delete the pod with {{delete-action}}\n - reset the analysis with {{reset-action}}"
    multiple-template: "Looks like {{pod-namespace}}/{{pod-name}} has a match with multiple rules, such as {{rule-description-0}}, {{rule-description-1}} and so on.  I could do the following:\n\n - delete the pod with {{delete-action}}\n - reset the analysis with {{reset-action}}"
  slack:
    enabled: false
    url: endpoint-for-slack-goes-here
    single-template: "Help!\nLooks like {{pod-namespace}}/{{pod-name}} has a match with {{rule-description}}. Should I do something about it?\n - Yes, <{{delete-action}}|delete> the pod\n - Nah, <{{reset-action}}|false alarm>"
    multiple-template: "Help!\nLooks like {{pod-namespace}}/{{pod-name}} has a match with multiple rules, such as {{rule-description-0}}, {{rule-description-1}} and so on. Should I do something about it?\n - Yes, <{{delete-action}}|delete> the pod\n - Nah, <{{reset-action}}|false alarm>"
