server.port: 8080

general:
  base-url: http://localhost:8080

k8s:
  watch:
    scheduled: 60000
    setup: 600000

watchfor:
  log-rules:
  - name: generic-exception-check
    description: a generic check to find Exceptions
    matches-in-or:
    - how-many: 3
      how-much: 120000
      values-in-and:
      - Caused by
    - how-many: 3
      how-much: 120000
      values-in-and:
      - Exception
    selectors-in-and:
    - namespace-match:
      - development
      
  status-rules:
  - name: generic-check-status
    description: a generic check to find status Errors
    matches-in-or:
    - on-restart: true
      on-error: true
      on-pending: true
      error-threshold: 30000
      pending-threshold: 30000
    selectors-in-and:
    - namespace-match:
      - development

handlers:
  delete-pod:
    enabled: true
  reset-analysis:
    enabled: true

notifiers:
  noop:
    enabled: true
    single-template: |
      Looks like {{pod-namespace}}/{{pod-name}} has a match with: {{rule-description}}.
      --- match explanation ---
      {{satisfied-explanation}}
      ---
      I could do the following:
      - delete the pod with {{delete-action}}
      - reset the analysis with {{reset-action}}
    multiple-template: |
      Looks like {{pod-namespace}}/{{pod-name}} has a match with multiple rules, such as: {{rule-description-0}}, {{rule-description-1}} and so on.
      --- first match explanation ---
      {{satisfied-explanation-0}}
      ---
      I could do the following:
      - delete the pod with {{delete-action}}
      - reset the analysis with {{reset-action}}
  slack:
    enabled: false
    url: endpoint-for-slack-goes-here
    single-template: |
      Help!
      Looks like {{pod-namespace}}/{{pod-name}} has a match with: {{rule-description}}.
      ```
      {{satisfied-explanation}}
      ```
      Should I do something about it?
      - Yes, <{{delete-action}}|delete> the pod
      - Nah, <{{reset-action}}|false alarm>
    multiple-template: |
      Help!
      Looks like {{pod-namespace}}/{{pod-name}} has a match with multiple rules, such as: {{rule-description-0}}, {{rule-description-1}} and so on.
      ```
      {{satisfied-explanation-0}}
      ```
      Should I do something about it?
      - Yes, <{{delete-action}}|delete> the pod
      - Nah, <{{reset-action}}|false alarm>
