server.port: 8080

general:
  base-url: http://localhost:8080

k8s:
  watch:
    scheduled: 60000
    setup: 600000

watchfor:
  log-rules:
  - name: Check for Exceptions
    description: check of an Exception
    matches-in-and:
    - how-many: 3
      how-much: 120000
      values-in-and:
      - ERROR
      - Caused by
    selectors-in-and:
    - namespace-match:
      - development

handlers:
  delete-pod:
    enabled: true

notifiers:
  noop:
    enabled: true
    template: "Help!\n\nLooks like {{pod-namespace}}/{{pod-name}} has a match with rule {{rule-name}}. I can do the following:\n\n - delete the pod with {{delete-action}}"
  slack:
    enabled: false
    url: endpoint-for-slack-here
    template: "Help!\n\nLooks like {{pod-namespace}}/{{pod-name}} has a match with rule {{rule-name}}. I can do the following:\n\n - Yes, delete the pod {{delete-action}}"