apiVersion: v1
kind: ConfigMap
metadata:  
  name: {{ include "noisy-nosy.fullname" . }}
  labels:
    {{- include "noisy-nosy.labels" . | nindent 4 }}
data:
  {{- if .Values.configurations }}
  application.yml: {{ .Values.configurations | toYaml | quote }}
  {{- end }}
